name: Recuperar thumbnails do YouTube

on:
  workflow_dispatch:

jobs:
  update-imageurl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install requests

      - name: Recuperar thumbnails
        env:
          BASEROW_TOKEN: ${{ secrets.BASEROW_TOKEN }}
          TABLE_ID: ${{ secrets.BASEROW_TABLE_ID }}
        run: python update_ImageUrl.py
